import{a as L,S as v,i as y}from"./assets/vendor-89feecc5.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&o(u)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const S=document.querySelector(".custom-input"),E=document.querySelector(".custom-button"),p=document.querySelector(".load-more-btn"),g=document.querySelector(".gallery-container"),i=document.querySelector(".loading-overlay"),M="41313291-32cdbbed0c1b146ceb687e8ad",l=40;let s=1,d="",f=0;async function m(e,n){const a="https://pixabay.com/api/",o=new URLSearchParams({key:M,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:l});try{return(await L.get(`${a}?${o}`)).data}catch(t){throw new Error(t)}}function h(e){const n=e.map(o=>`
        <a href="${o.largeImageURL}" class="image-card">
          <img src="${o.webformatURL}" alt="${o.tags}">
          <div class="image-info">
            <p>Likes: ${o.likes}</p>
            <p>Views: ${o.views}</p>
            <p>Comments: ${o.comments}</p>
            <p>Downloads: ${o.downloads}</p>
          </div>
        </a>
      `).join("");g.insertAdjacentHTML("beforeend",n),new v(".gallery-container a",{captionsData:"alt",captionsDelay:250}).refresh()}function c(e){y.error({title:"Something wrong",message:e,position:"topRight",progressBarColor:"rgb(255, 0, 0)"})}function $(e){y.info({title:"Something wrong",message:e,position:"topRight",progressBarColor:"rgb(255, 0, 0)"})}function b(){p.style.display="block"}function w(){p.style.display="none"}function k(){$("We're sorry, but you've reached the end of search results.")}async function q(){if(!(i.style.display==="flex"||s*l>=f)){i.style.display="flex",s++;try{const e=await m(s,d);e.hits&&e.hits.length>0?(h(e.hits),e.totalHits>s*l?b():(w(),k())):c("No images found.")}catch{c("Error loading more images.")}finally{i.style.display="none"}}}E.addEventListener("click",async()=>{d=S.value.trim(),s=1,f=0,g.innerHTML="",i.style.display="flex";try{const e=await m(s,d);e.hits&&e.hits.length>0?(h(e.hits),f=e.totalHits,e.totalHits>l?b():w()):c("No images found.")}catch{c("Error searching for images.")}finally{i.style.display="none"}});p.addEventListener("click",q);
//# sourceMappingURL=commonHelpers.js.map
